name: Deploy Pages
on:
  push:
    branches:
      - main
jobs:
  deploy_production:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    timeout-minutes: 10
    environment:
      name: production
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy Page
        uses: cloudflare/pages-action@v1
        with:
          wranglerVersion: "3.70.0"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: redirectchecker
          # wrangler.toml pages_build_output_dir
          directory: .vercel/output/static
          branch: main