name: Deploy Pages
on:
  push:
    branches:
      - main
jobs:
  deploy_production:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    timeout-minutes: 10
    environment:
      name: production
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Deploy to Cloudflare Pages
        run: |
          npx wrangler pages project create redirectchecker --production-branch main
          npm run deploy 
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
